{{ if .Values.certManagerCertificate}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "reactive-resume.fullname" . }}
spec:
  commonName: {{ .Values.certManagerCertificate.commonName }}
  dnsNames:
    {{- toYaml .Values.certManagerCertificate.dnsNames | nindent 4 }} 
  issuerRef:
    kind: {{ .Values.certManagerCertificate.issuer.kind }}
    name: {{ .Values.certManagerCertificate.issuer.name }}
  secretName: {{ .Values.certManagerCertificate.secretName }}
{{ end }}
